### ISSUE TITLE
SPRAV .bat installer

### ISSUE THREAD

**Issue by SkajpCZ** [xxcosita3czxx/MC-PC-AC#1]
![image](https://user-images.githubusercontent.com/103284636/218282265-99c9bab6-2d64-496e-9587-40e5425860c1.png)

zmen to z `pyinstaller`
na `python -m PyInstaller`

diky ;)

**Comment by xxcosita3czxx** [comment]
No vydím v tom malý problém s tím že pyinstaller jako příkaz je script, a nie modul, ale urobim to, thanks

**Comment by xxcosita3czxx** [comment]
Fixd
